version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  - cmd: git config --global core.autocrlf true
install:
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v4.0.0/nuget.exe 
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./efcore-include-helper/ef_includer.csproj --verbosity m
build_script:
  - cmd: dotnet build ./efcore-include-helper/ef_includer.csproj 
  - cmd: dotnet pack  -c Release /p:PackageVersion=1.0.{build} 
artifacts:
- path: ./efcore-include-helper/bin/Release/*.nupkg
  name: NuGet
deploy:
- provider: NuGet
    api_key:
    secure: odO06iUThLr3doXPGox3Ug12sUYRvCWzAlWeEIjJ/Jq/Exn3q4p0igOfXX38gH/R
  skip_symbols: true